
#   BTREE_FRAMEWORK_FOUND			- asserted if BTREE_FRAMEWORK has been found
#   BTREE_FRAMEWORK_PREFIX			- location of the btree framework
#   BTREE_FRAMEWORK_INCLUDE_DIRS	- include locations of BTREE_FRAMEWORK
#   BTREE_FRAMEWORK_LIBRARIES		- libraries produced by BTREE_FRAMEWORK

if (NOT DEFINED BTREE_FRAMEWORK_PREFIX)
	get_filename_component (BTREE_FRAMEWORK_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
endif ()

set (BTREE_FRAMEWORK_FOUND				TRUE)
set (BTREE_FRAMEWORK_INCLUDE_DIRS		${BTREE_FRAMEWORK_PREFIX} ${BTREE_FRAMEWORK_PREFIX}/specific_data_classes ${BTREE_FRAMEWORK_PREFIX}/io/data_layer/target ${BTREE_FRAMEWORK_PREFIX}/io/properties)
set (BTREE_FRAMEWORK_LIBRARIES			btree_framework)

mark_as_advanced (BTREE_FRAMEWORK_INCLUDE_DIRS BTREE_FRAMEWORK_LIBRARIES)
